spring:
  application:
    name: IReviewMovies
  profiles:
    active: #spring.profiles.active#
  flyway:
    migration

application:
  tmdbApiKey: "aa9490e023b69dc39241ba00b1fa101d"
  movieApiUrl: "https://api.themoviedb.org/3/search/movie"
