spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:8889/ireviewmovies?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

